name: bmi_calculator_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  image_picker: ^1.2.3
  image: ^4.5.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/appIcon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/appIcon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/appIcon.png

dependency_overrides:
  win32: ^5.10.1
  flutter_plugin_android_lifecycle: ^2.0.35
  image_picker_android: ^0.8.13+19
  shared_preferences_android: ^2.4.26